name: igpl_monday_app
description: Real Estate CRM System for IGPL Monday.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust based on your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.18.0
  firebase_messaging: ^14.8.0

  # State Management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^13.2.4

  # UI & Icons
  lucide_icons: ^0.257.0 # Corrected version based on previous error suggestion
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

  # Charts & Data Grids
  syncfusion_flutter_charts: ^25.2.6
  syncfusion_flutter_datagrid: ^25.2.6
  syncfusion_flutter_core: ^25.2.6 # Added this as it's often a dependency for datagrid

  # Local Notifications
  flutter_local_notifications: ^17.0.0

  # Utility
  intl: ^0.19.0
  uuid: ^4.4.0

  # Cupertino Icons (often included by default)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Or your preferred linter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700