dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^12.1.3
  
  # UI & Design
  google_fonts: ^6.1.0
  lucide_icons: ^0.294.0
  flutter_animate: ^4.5.0
  
  # Charts & Tables
  syncfusion_flutter_charts: ^24.1.41
  syncfusion_flutter_datagrid: ^24.1.41
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  
  # Notifications
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7