// File generated by FlutterFire CLI.
// For more information, see: https://firebase.google.com/docs/cli/references/flutterfire-cli#set_up_a_flutter_project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI command `flutterfire configure`.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI command `flutterfire configure`.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI command `flutterfire configure`.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjjZ5CWKKCOZYFzixH6HzxLoJ2OK6QbJp',
    appId: 'YOUR_WEB_APP_ID', // Not provided in screenshots
    messagingSenderId: '369016013249', // Project number from web console
    projectId: 'igplmonday',
    authDomain: 'igplmonday.firebaseapp.com', // Common pattern for Firebase projects
    databaseURL: 'https://igplmonday-default-rtdb.firebaseio.com', // Common pattern for Firebase projects
    storageBucket: 'igplmonday.appspot.com', // Common pattern for Firebase projects
    // measurementId: 'YOUR_WEB_MEASUREMENT_ID', // Optional
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjjZ5CWKKCOZYFzixH6HzxLoJ2OK6QbJp',
    appId: '1:369016013249:android:3c809d1ddc2d6b0c7cef40',
    messagingSenderId: '369016013249',
    projectId: 'igplmonday',
    databaseURL: 'https://igplmonday-default-rtdb.firebaseio.com', // Common pattern for Firebase projects
    storageBucket: 'igplmonday.appspot.com', // Common pattern for Firebase projects
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Not provided in screenshots
    appId: 'YOUR_IOS_APP_ID', // Not provided in screenshots
    messagingSenderId: '369016013249', // Project number from web console
    projectId: 'igplmonday',
    databaseURL: 'https://igplmonday-default-rtdb.firebaseio.com', // Common pattern for Firebase projects
    storageBucket: 'igplmonday.appspot.com', // Common pattern for Firebase projects
    // bundleId: 'YOUR_IOS_BUNDLE_ID', // Optional
    // clientId: 'YOUR_IOS_CLIENT_ID', // Optional (for Google Sign-in)
  );
}